<a href="https://colab.research.google.com/github/Harsh28-raj/dl_/blob/main/legal_case_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!mkdir -p ~/.kaggle

!cp kaggle.json ~/.kaggle/

!chmod 600 ~/.kaggle/kaggle.json

In [2]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (1.7.4.5)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2026.2.25)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.4.5)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.11)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from kaggle) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.5.1)

In [3]:
!kaggle datasets download -d vangap/indian-supreme-court-judgments

Dataset URL: https://www.kaggle.com/datasets/vangap/indian-supreme-court-judgments
License(s): CC-BY-NC-SA-4.0
Downloading indian-supreme-court-judgments.zip to /content
100% 4.75G/4.77G [01:10<00:00, 270MB/s]
100% 4.77G/4.77G [01:10<00:00, 73.1MB/s]

In [4]:
!unzip indian-supreme-court-judgments.zip judgments.csv

Archive:  indian-supreme-court-judgments.zip
  inflating: judgments.csv

In [5]:
import pandas as pd

df=pd.read_csv("judgments.csv")

df.head()

,diary_no,Judgement_type,case_no,pet,res,pet_adv,res_adv,bench,judgement_by,judgment_dates,temp_link,language
0,5-2021,J,MA-000083 - 2021,UNION OF INDIA,ASSOCIATION OF UNIFIED TELECOM SERVICEPROVIDER...,B. VIJAYALAKSHMI MENON,NaN,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,23-07-2021,supremecourt/2021/5/5_2021_36_1501_28814_Judge...,NaN
1,28-2021,J,C.A. No.-000867-000867 - 2021,INDEX MEDICAL COLLEGE HOSPITAL AND RESEARCH CE...,THE STATE OF MADHYA PRADESH,NISHIT AGRAWAL,NaN,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,03-02-2021,supremecourt/2021/28/28_2021_38_14_25922_Judge...,NaN
2,70-2020,J,Crl.A. No.-000167-000167 - 2021,ARCHANA RANA,THE STATE OF UTTAR PRADESH,SANJEEV MALHOTRA,NaN,"HON'BLE THE CHIEF JUSTICE, HON'BLE MR. JUSTICE...",HON'BLE THE CHIEF JUSTICE,01-03-2021,supremecourt/2020/70/70_2020_36_1503_26554_Jud...,NaN
3,82-2021,J,SLP(C) No.-000811 - 2021,THE EMPLOYEES STATE INSURANCE CORPORATION,M/S. TEXMO INDUSTRIES,MRIDULA RAY BHARADWAJ,NaN,"HON'BLE MS. JUSTICE INDIRA BANERJEE, HON'BLE M...",HON'BLE MS. JUSTICE INDIRA BANERJEE,08-03-2021,supremecourt/2021/82/82_2021_43_13_26745_Judge...,NaN
4,114-2021,J,C.A. No.-000390-000390 - 2021,KALOJI NARAYANA RAO UNIVERSITY OF HEALTH SCIENCES,SRIKEERTI REDDI PINGLE,VENKAT PALWAI LAW ASSOCIATES,NaN,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE S. RAVINDRA BHAT,16-02-2021,supremecourt/2021/114/114_2021_38_1501_26229_J...,NaN

In [6]:
!rm indian-supreme-court-judgments.zip

In [24]:
df.sample(1000)

,case_no,pet_adv,bench,judgement_by,judgment_dates
8470,Crl.A. No.-001242-001242 - 2017,BIJAN KUMAR GHOSH,"HON'BLE MR. JUSTICE ARUN MISHRA, HON'BLE MR. J...",HON'BLE MR. JUSTICE ARUN MISHRA,27-07-2017
9406,Crl.A. No.-000926-000926 - 2018,PETITIONER-IN-PERSON,"HON'BLE MR. JUSTICE KURIAN JOSEPH, HON'BLE MR....",HON'BLE MR. JUSTICE KURIAN JOSEPH,23-07-2018
24014,C.A. No.-004928 - 2018,MUKESH KUMAR MARORIA,"HON'BLE MR. JUSTICE M.R. SHAH, HON'BLE MRS. JU...",HON'BLE MR. JUSTICE M.R. SHAH,11-07-2022
46432,C.A. No.-005653-005653 - 2014,PRAVEEN SWARUP,"HON'BLE MR. JUSTICE ANIL R. DAVE, HON'BLE MR. ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,10-08-2016
9015,C.A. No.-006653-006653 - 2018,SUDHA GUPTA,"HON'BLE MR. JUSTICE KURIAN JOSEPH, HON'BLE MR....",HON'BLE MR. JUSTICE KURIAN JOSEPH,13-07-2018
...,...,...,...,...,...
23903,C.A. No.-007181-007181 - 2022,ABID ALI BEERAN P,"HON'BLE MR. JUSTICE DINESH MAHESHWARI, HON'BLE...",HON'BLE MR. JUSTICE DINESH MAHESHWARI,29-09-2022
7467,C.A. No.-008943-008943 - 2017,J S WAD AND CO,"HON'BLE MR. JUSTICE ABHAY MANOHAR SAPRE, HON'B...",HON'BLE MR. JUSTICE ABHAY MANOHAR SAPRE,11-07-2017
266,C.A. No.-002899-002899 - 2021,ANUP KUMAR,"HON'BLE MR. JUSTICE R. SUBHASH REDDY, HON'BLE ...",HON'BLE MR. JUSTICE R. SUBHASH REDDY,15-12-2021
9756,W.P.(Crl.) No.-000194 - 2017,SUVIDUTT M.S.,"HON'BLE THE CHIEF JUSTICE, HON'BLE MR. JUSTICE...",HON'BLE THE CHIEF JUSTICE,27-09-2018
25180,W.P.(C) No.-000196 - 2018,KHAITAN & CO.,"HON'BLE MR. JUSTICE ARUN MISHRA, HON'BLE MS. J...",HON'BLE MR. JUSTICE M.R. SHAH,31-08-2020

In [25]:
df.shape

(8094, 5)

In [26]:
df.columns

Index(['case_no', 'pet_adv', 'bench', 'judgement_by', 'judgment_dates'], dtype='object')

In [27]:
df=df.drop([
'diary_no',
'Judgement_type',
'pet',
'res',
'res_adv',
'temp_link',
'language'
],axis=1)

KeyError: "['diary_no', 'Judgement_type', 'pet', 'res', 'res_adv', 'temp_link', 'language'] not found in axis"

In [28]:
df.head()

,case_no,pet_adv,bench,judgement_by,judgment_dates
0,MA-000083 - 2021,B. VIJAYALAKSHMI MENON,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,23-07-2021
1,C.A. No.-000867-000867 - 2021,NISHIT AGRAWAL,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,03-02-2021
2,Crl.A. No.-000167-000167 - 2021,SANJEEV MALHOTRA,"HON'BLE THE CHIEF JUSTICE, HON'BLE MR. JUSTICE...",HON'BLE THE CHIEF JUSTICE,01-03-2021
3,SLP(C) No.-000811 - 2021,MRIDULA RAY BHARADWAJ,"HON'BLE MS. JUSTICE INDIRA BANERJEE, HON'BLE M...",HON'BLE MS. JUSTICE INDIRA BANERJEE,08-03-2021
4,C.A. No.-000390-000390 - 2021,VENKAT PALWAI LAW ASSOCIATES,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE S. RAVINDRA BHAT,16-02-2021

In [29]:
df.dropna()

,case_no,pet_adv,bench,judgement_by,judgment_dates
0,MA-000083 - 2021,B. VIJAYALAKSHMI MENON,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,23-07-2021
1,C.A. No.-000867-000867 - 2021,NISHIT AGRAWAL,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,03-02-2021
2,Crl.A. No.-000167-000167 - 2021,SANJEEV MALHOTRA,"HON'BLE THE CHIEF JUSTICE, HON'BLE MR. JUSTICE...",HON'BLE THE CHIEF JUSTICE,01-03-2021
3,SLP(C) No.-000811 - 2021,MRIDULA RAY BHARADWAJ,"HON'BLE MS. JUSTICE INDIRA BANERJEE, HON'BLE M...",HON'BLE MS. JUSTICE INDIRA BANERJEE,08-03-2021
4,C.A. No.-000390-000390 - 2021,VENKAT PALWAI LAW ASSOCIATES,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE S. RAVINDRA BHAT,16-02-2021
...,...,...,...,...,...
47105,C.A. No.-004715-004715 - 2011,SANJAY KAPUR,"HON'BLE MR. JUSTICE T.S. THAKUR, HON'BLE MR. J...",HON'BLE MR. JUSTICE A.M. KHANWILKAR,16-09-2016
47106,C.A. No.-004715-004715 - 2011,SANJAY KAPUR,"HON'BLE MR. JUSTICE T.S. THAKUR, HON'BLE MR. J...",HON'BLE MR. JUSTICE A.M. KHANWILKAR,16-09-2016
47169,C.A. No.-010860-010860 - 2016,CYRIL AMARCHAND MANGALDAS AOR,"HON'BLE MR. JUSTICE KURIAN JOSEPH, HON'BLE MR....",HON'BLE MR. JUSTICE ROHINTON FALI NARIMAN,15-11-2016
47170,C.A. No.-010860-010860 - 2016,CYRIL AMARCHAND MANGALDAS AOR,"HON'BLE MR. JUSTICE KURIAN JOSEPH, HON'BLE MR....",HON'BLE MR. JUSTICE ROHINTON FALI NARIMAN,15-11-2016
47236,C.A. No.-010951-010951 - 2016,SHARMILA UPADHYAY,"HON'BLE MR. JUSTICE A.K. SIKRI, HON'BLE MRS. J...",HON'BLE MR. JUSTICE A.K. SIKRI,14-12-2016

In [30]:
df.shape

(8094, 5)

In [31]:
df.head()

,case_no,pet_adv,bench,judgement_by,judgment_dates
0,MA-000083 - 2021,B. VIJAYALAKSHMI MENON,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,23-07-2021
1,C.A. No.-000867-000867 - 2021,NISHIT AGRAWAL,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,03-02-2021
2,Crl.A. No.-000167-000167 - 2021,SANJEEV MALHOTRA,"HON'BLE THE CHIEF JUSTICE, HON'BLE MR. JUSTICE...",HON'BLE THE CHIEF JUSTICE,01-03-2021
3,SLP(C) No.-000811 - 2021,MRIDULA RAY BHARADWAJ,"HON'BLE MS. JUSTICE INDIRA BANERJEE, HON'BLE M...",HON'BLE MS. JUSTICE INDIRA BANERJEE,08-03-2021
4,C.A. No.-000390-000390 - 2021,VENKAT PALWAI LAW ASSOCIATES,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE S. RAVINDRA BHAT,16-02-2021

In [32]:
df.head()

,case_no,pet_adv,bench,judgement_by,judgment_dates
0,MA-000083 - 2021,B. VIJAYALAKSHMI MENON,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,23-07-2021
1,C.A. No.-000867-000867 - 2021,NISHIT AGRAWAL,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,03-02-2021
2,Crl.A. No.-000167-000167 - 2021,SANJEEV MALHOTRA,"HON'BLE THE CHIEF JUSTICE, HON'BLE MR. JUSTICE...",HON'BLE THE CHIEF JUSTICE,01-03-2021
3,SLP(C) No.-000811 - 2021,MRIDULA RAY BHARADWAJ,"HON'BLE MS. JUSTICE INDIRA BANERJEE, HON'BLE M...",HON'BLE MS. JUSTICE INDIRA BANERJEE,08-03-2021
4,C.A. No.-000390-000390 - 2021,VENKAT PALWAI LAW ASSOCIATES,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE S. RAVINDRA BHAT,16-02-2021

In [33]:
lawyer_counts=df['pet_adv'].value_counts()

In [34]:
lawyer_counts

pet_adv
PETITIONER-IN-PERSON    90
ANIL KATIYAR            90
MUKESH KUMAR MARORIA    80
E. C. AGRAWALA          77
B. KRISHNA PRASAD       74
                        ..
SAROJ TRIPATHI           1
SRIDEVI PANIKKAR         1
GAURAV DHINGRA           1
ACM LEGAL                1
LEMAX LAWYERS & CO.      1
Name: count, Length: 1370, dtype: int64

In [35]:
import numpy as np

In [39]:
df=df.dropna()

In [41]:
print(df.columns)

Index(['case_no', 'pet_adv', 'bench', 'judgement_by', 'judgment_dates'], dtype='object')

In [42]:
def get_case_type(x):

    x=str(x)

    if "Crl" in x:
        return 0
    elif "C.A" in x:
        return 1
    elif "SLP" in x:
        return 2
    elif "W.P" in x:
        return 3
    else:
        return 4

df['case_type']=df['case_no'].apply(get_case_type)

In [43]:
lawyer_counts=df['pet_adv'].value_counts()

df['lawyer_exp']=df['pet_adv'].map(lawyer_counts)

df['lawyer_exp']=df['lawyer_exp']/df['lawyer_exp'].max()

In [44]:
judge_counts=df['judgement_by'].value_counts()

df['judge_exp']=df['judgement_by'].map(judge_counts)

df['judge_exp']=df['judge_exp']/df['judge_exp'].max()

In [45]:
df['judge_count']=df['bench'].str.count("JUSTICE")+1

In [46]:
df['complexity'] = df['judge_count']*2 + np.random.randint(5,20,len(df))

df['evidence']=np.random.uniform(0.4,0.9,len(df))

df['win_score']=(
0.30*df['lawyer_exp']+
0.30*df['judge_exp']+
0.20*df['evidence']+
0.20*(1/(df['complexity']/10))
)

df['win_score']=df['win_score'].clip(0.05,0.95)

df['outcome']=np.random.binomial(1,df['win_score'])

In [47]:
FEATURES=[
'case_type',
'lawyer_exp',
'judge_exp',
'judge_count',
'complexity',
'evidence'
]

X=df[FEATURES]

y=df['outcome']

In [48]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(
X,
y,
test_size=0.2,
stratify=y,
random_state=42
)

In [49]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

X_train=scaler.fit_transform(X_train)

X_test=scaler.transform(X_test)

In [50]:
from sklearn.linear_model import LogisticRegression

log_model=LogisticRegression(
max_iter=2000,
C=0.3,
random_state=42
)

log_model.fit(X_train,y_train)

LogisticRegression(C=0.3, max_iter=2000, random_state=42)

In [51]:
from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier(
n_estimators=300,
max_depth=10,
random_state=42
)

rf.fit(X_train,y_train)

RandomForestClassifier(max_depth=10, n_estimators=300, random_state=42)

In [52]:
from xgboost import XGBClassifier

xgb=XGBClassifier(
n_estimators=300,
learning_rate=0.05,
max_depth=6,
random_state=42
)

xgb.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_parallel_tree=None, ...)

In [53]:
from sklearn.metrics import accuracy_score

log_pred=log_model.predict(X_test)

rf_pred=rf.predict(X_test)

xgb_pred=xgb.predict(X_test)

print("Logistic:",accuracy_score(y_test,log_pred))

print("RF:",accuracy_score(y_test,rf_pred))

print("XGB:",accuracy_score(y_test,xgb_pred))

Logistic: 0.6528721432983323
RF: 0.6429894996911674
XGB: 0.6331068560840025

In [54]:
prob=log_model.predict_proba(X_test)

print(prob[:5])

[[0.56208225 0.43791775]
 [0.67411386 0.32588614]
 [0.6986597  0.3013403 ]
 [0.7224351  0.2775649 ]
 [0.73624742 0.26375258]]

In [55]:
def predict_case(case_type,lawyer_exp,judge_exp,judge_count,complexity,evidence):

    sample=pd.DataFrame(
        [[case_type,lawyer_exp,judge_exp,judge_count,complexity,evidence]],
        columns=FEATURES
    )

    sample=scaler.transform(sample)

    prob=log_model.predict_proba(sample)

    win=float(prob[0][1]*100)

    if win>70:
        strength="Strong"

    elif win>50:
        strength="Moderate"

    else:
        strength="Weak"

    return {
        "Win probability":round(win,2),
        "Case strength":strength
    }

In [56]:
predict_case(1,0.3,0.5,3,18,0.7)

{'Win probability': 50.49, 'Case strength': 'Moderate'}

In [57]:
log_model.fit(X_train,y_train)
rf.fit(X_train,y_train)
xgb.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_parallel_tree=None, ...)

In [58]:
from sklearn.metrics import accuracy_score,classification_report,f1_score

models={
    "Logistic Regression":log_model,
    "Random Forest":rf,
    "XGBoost":xgb
}

for name,model in models.items():

    pred=model.predict(X_test)

    acc=accuracy_score(y_test,pred)

    f1=f1_score(y_test,pred)

    print("======",name,"======")

    print("Accuracy:",round(acc*100,2),"%")

    print("F1 Score:",round(f1*100,2),"%")

    print(classification_report(y_test,pred))

    print()

====== Logistic Regression ======
Accuracy: 65.29 %
F1 Score: 46.88 %
              precision    recall  f1-score   support

           0       0.67      0.83      0.74       974
           1       0.60      0.38      0.47       645

    accuracy                           0.65      1619
   macro avg       0.64      0.61      0.61      1619
weighted avg       0.64      0.65      0.63      1619


====== Random Forest ======
Accuracy: 64.3 %
F1 Score: 43.99 %
              precision    recall  f1-score   support

           0       0.66      0.84      0.74       974
           1       0.59      0.35      0.44       645

    accuracy                           0.64      1619
   macro avg       0.62      0.59      0.59      1619
weighted avg       0.63      0.64      0.62      1619


====== XGBoost ======
Accuracy: 63.31 %
F1 Score: 43.96 %
              precision    recall  f1-score   support

           0       0.66      0.81      0.73       974
           1       0.56      0.36      0.44       645

    accuracy                           0.63      1619
   macro avg       0.61      0.59      0.58      1619
weighted avg       0.62      0.63      0.61      1619

In [59]:
results=[]

for name,model in models.items():

    pred=model.predict(X_test)

    acc=accuracy_score(y_test,pred)

    f1=f1_score(y_test,pred)

    results.append([name,acc,f1])

results_df=pd.DataFrame(
results,
columns=["Model","Accuracy","F1 Score"]
)

results_df

                 Model  Accuracy  F1 Score
0  Logistic Regression  0.652872  0.468809
1        Random Forest  0.642989  0.439922
2              XGBoost  0.633107  0.439623

In [60]:
from sklearn.metrics import roc_auc_score

for name,model in models.items():

    prob=model.predict_proba(X_test)[:,1]

    auc=roc_auc_score(y_test,prob)

    print(name,"ROC AUC:",round(auc,3))

Logistic Regression ROC AUC: 0.666
Random Forest ROC AUC: 0.659
XGBoost ROC AUC: 0.625

In [64]:
predict_case(1,0,0,0,18,0.7)

{'Win probability': 31.64, 'Case strength': 'Weak'}